certs:
  - "mjdawson.net":
      - cert: "/etc/letsencrypt/live/mjdawson.net-0001/fullchain.pem"
        key: "/etc/letsencrypt/live/mjdawson.net-0001/privkey.pem"
  - "*.mjdawson.net":
      - cert: "/etc/letsencrypt/live/mjdawson.net-0001/fullchain.pem"
        key: "/etc/letsencrypt/live/mjdawson.net-0001/privkey.pem"
